apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp-deployment
  labels:
    app: flask-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-webapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
        - name: flask-webapp
          image: surajgthakur/flask_webapp_suraj:v3
          ports:
            - containerPort: 8080
