apiVersion: v1
kind: Service
metadata:
  name: flask-webapp-service
spec:
  selector:
    app: flask-webapp
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
    nodePort: 30007
  type: NodePort
